---
title: "About Me"
about:
  template: solana
  image: aboutPic.HEIC
  links:
    - icon: envelope-fill
      text: Email
      href: "mailto:vivek.sriram@gmail.com"
    - icon: twitter
      text: Twitter
      href: https://twitter.com/viveksrm24
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/vivek-sriram/
    - icon: github
      text: GitHub
      href: https://github.com/vsriram24
    - icon: mortarboard-fill
      text: Google Scholar
      href: https://scholar.google.com/citations?user=ZN4ZFuUAAAAJ&hl=en
---

I currently work as a clinical data scientist at the [Fred Hutchinson Cancer Center](https://www.fredhutch.org/en.html) Data Science Lab \([DaSL](https://hutchdatascience.org)\) in Seattle, WA. My role focuses on the development and productization of statistical models and machine learning systems for electronic phenotyping and cohort identification across the institution. I also serve as a guest lecturer in the [Department of Biostatistics, Epidemiology, and Informatics](https://www.dbei.med.upenn.edu) at the [University of Pennsylvania](https://www.upenn.edu) and a collaborator with the [Health Futures Group](https://www.microsoft.com/en-us/research/lab/microsoft-health-futures/) at [Microsoft Research](https://www.microsoft.com/en-us/research/).

Prior to my position at Fred Hutch, I completed my Ph.D. and postdoctoral training in [Biomedical Informatics and Computational Genomics](https://www.med.upenn.edu/gcb/) at the University of Pennsylvania [Perelman School of Medicine](https://www.med.upenn.edu). There, I worked with Dr. [Dokyoon Kim](https://www.med.upenn.edu/apps/faculty/index.php/g275/p9240045)’s [Integrative 'Omics and Biomedical Informatics Lab](https://www.biomedinfolab.com), developing machine learning and graph-based methods to identify genetic contributors to disease comorbidities from large-scale multimodal biomedical data (You can listen to a recording of my public thesis defense [here](https://mediasite.med.upenn.edu/mediasite/Play/d78f6d5d76bf4a9c8b673f5c3ba858d61d)!) 

In addition to my doctoral degree, I hold a M.A. in Statistics and Data Science from the [Wharton School of Business](https://www.wharton.upenn.edu), as well as a B.Sc. with honors in Statistics, a B.Sc. in Computer Science, and a minor in Computational Biology from [Duke University](https://duke.edu).



